### ISSUE TITLE
执行最后命令前，可以给下操作指引吗？比如怎么编译等。go小白一枚

### ISSUE THREAD

**Issue by liky88** [Bpazy/OhMyAppleStore#3]

**Comment by Bpazy** [comment]
直接下载 Release 不可以么？[https://github.com/Bpazy/OhMyAppleStore/releases](https://github.com/Bpazy/OhMyAppleStore/releases)

编译的话参考 Github Actions 里面的配置即可: https://github.com/Bpazy/OhMyAppleStore/blob/76f111c3731962bb6035e06ddba281d85e57edad/.github/workflows/build-release.yml#L20

**Comment by liky88** [comment]
macXXX:OhMyAppleStore XXX$ sh oh-my-apple-store-linux-amd64 loop
**oh-my-apple-store-linux-amd64: oh-my-apple-store-linux-amd64: cannot execute binary file**

运行不了？

**Comment by Bpazy** [comment]
你这是 MacOS？那你应该下载 Mac 版本

**Comment by liky88** [comment]
你没有打macos的版本哦。。打一个上去？

**Comment by Bpazy** [comment]
darwin 就是: https://github.com/Bpazy/OhMyAppleStore/releases/download/v1.0.1/oh-my-apple-store-darwin-amd64

**Comment by liky88** [comment]
macliky:OhMyAppleStore Liky$ sh oh-my-apple-store-darwin-amd64 loop
oh-my-apple-store-darwin-amd64: oh-my-apple-store-darwin-amd64: cannot execute binary file

一样的错误哦。

**Comment by Bpazy** [comment]
你应该: `./oh-my-apple-store-darwin-amd64 loop`
而不是: `sh oh-my-apple-store-darwin-amd64 loop`

**Comment by liky88** [comment]
dingtalk:
  token: 
  secret:
