### ISSUE TITLE
panic: no token

### ISSUE THREAD

**Issue by SuXin1039** [Bpazy/OhMyAppleStore#4]
您好，我使用您的代码，这边启动的时候 一直抛出 panic: no token 这个异常，请问这个应该如何处理呢。万分感谢

**Comment by Bpazy** [comment]
配置文件中钉钉相关的填上
![image](https://user-images.githubusercontent.com/9838749/135055182-e8e15c2f-6e34-4776-b1f7-59b7c624c0d9.png)

**Comment by SuXin1039** [comment]
我配置了呀主要是，， 我可以加您的微信么
![image](https://user-images.githubusercontent.com/14151055/135055349-d2753750-8dae-4068-9e08-ff98a261f759.png)

**Comment by Bpazy** [comment]
配置文件位置不对吧，贴下配置文件的全路径看下

**Comment by SuXin1039** [comment]
很感谢您的回复，我在 loop.go 的文件中手动将内容走出了替换，也启动成功了 但是不知道为什么 好像轮询并没有开，我的钉钉没有收到机器人的消息。

**Comment by Bpazy** [comment]
轮训 30s 一次，只有检测到存在自提库存才会发送钉钉消息

**Comment by SuXin1039** [comment]
可以啦 谢谢您

**Comment by Bpazy** [comment]
👍
