### ISSUE TITLE
小白求教mac能用吗？

### ISSUE THREAD

**Issue by lxiaoboo** [Bpazy/OhMyAppleStore#5]

**Comment by Bpazy** [comment]
可以，drawin 版本就是

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
From: lxiaoboo ***@***.***>
Sent: Friday, October 1, 2021 10:26:23 AM
To: Bpazy/OhMyAppleStore ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Bpazy/OhMyAppleStore] 小白求教mac能用吗？ (#5)


―

**Comment by lxiaoboo** [comment]
下是下载了不知道咋用，我以为是直接双击就能运行的
