### ISSUE TITLE
运行了挺多报错的，大佬帮忙看看什么原因吗

### ISSUE THREAD

**Issue by lxiaoboo** [Bpazy/OhMyAppleStore#6]
MacBook-Pro:appstore tony$ ./oh-my-apple-store-darwin-amd64 loop
panic: no token

goroutine 1 [running]:
github.com/blinkbean/dingtalk.InitDingTalkWithSecret(...)
	/home/runner/go/pkg/mod/github.com/blinkbean/dingtalk@v0.0.0-20210905093040-7d935c0f7e19/webhook.go:30
github.com/Bpazy/oh-my-apple-store/cmd.glob..func1(0x17bcfc0, {0x145befa, 0x0, 0x0})
	/home/runner/work/OhMyAppleStore/OhMyAppleStore/cmd/loop.go:51 +0x6d2
github.com/spf13/cobra.(*Command).execute(0x17bcfc0, {0x17f5f10, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x17bd240)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/Bpazy/oh-my-apple-store/cmd.Execute()
	/home/runner/work/OhMyAppleStore/OhMyAppleStore/cmd/root.go:32 +0x25
main.main()
	/home/runner/work/OhMyAppleStore/OhMyAppleStore/main.go:21 +0x17

**Comment by Bpazy** [comment]
配置文件位置正确吗？其中的 token 配置了吗

**Comment by Bpazy** [comment]
没响应，先关闭了
