### ISSUE TITLE
大佬能帮忙部署一下呢

### ISSUE THREAD

**Issue by 578440613** [Bpazy/OhMyAppleStore#7]

**Comment by 578440613** [comment]
token 配置了，路径:/home/oh-my-apple-store.yaml    抛出 panic: no token 这个异常，能帮忙看看么。万分感谢

**Comment by Bpazy** [comment]
配置文件路径错了，不应该是 `/home`，应该是你当前用户的 home 路径。假设你的用户名称为 `myname`，则在 Linux 下路径应该为 `/home/myname`，在 windows 下则为 `C:\Users\myname`

**Comment by 578440613** [comment]
谢谢解答，我用的root用户名登录的，home底下没有root文件夹，我把路径改成/root/oh-my-apple-store.yaml还是不得行

**Comment by Bpazy** [comment]
应该是 `/root/.oh-my-apple-store.yaml` 哦，你的文件名前面少了个`点`

**Comment by 578440613** [comment]
万分感谢，解决了
